[package]
name = "viewport_3d"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy.workspace = true
pane_layout.workspace = true
camera_3d.workspace = true
styles.workspace = true
infinite_grid.workspace = true
bild_core.workspace = true
bevy_render.workspace = true

[lints]
workspace = true
