[package]
name = "interaction"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
bevy = { workspace = true }
camera = { workspace = true }
bitflags = { workspace = true }